[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.0",
    "cmake",
    "scikit_build @ git+https://github.com/YannickJadoul/scikit-build@vs2019",
]

build-backend = "setuptools.build_meta"
